spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customers
              uri: http://localhost:8080/
              predicates:
                - Path=/customers/**,/customer/**
            - id: accounts
              uri: http://localhost:8081/
              predicates:
                - Path=/accounts/**,/account/**

